# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run the deploy script.
# The deploy script publishes our build to gh-pages.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy to gh-pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'

    - run: npm ci
    - run: |
        git config --global user.name 'Niranjan Pradeep'
        git config --global user.email 'pradeepnschrodinger@users.noreply.github.com'
    - run: npm run deploy
