# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run the deploy script.
# The deploy script publishes our build to gh-pages.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy to gh-pages

on:
  release:
    types: [published]

jobs:
  # NOTE (pradeep): This job checks if the published release is a "stable release".
  # eg: v1.0.10 is stable, but not v1.0.10-experimental-foo
  # I'm also limiting this workflow to just the "v1" until we carve out separate gh-pages for each major release.
  check-release:
    name: Check if release is stable
    runs-on: ubuntu-latest

    # map step output to job output
    outputs: 
      is_stable: $ {{ steps.check-release-stable.outputs.is_stable }}

    steps:
    - name: Check if release is stable
      id: check-release-stable
      env:
        RELEASE_TAG: ${{ github.event.release.tag_name }} # The tag name. eg: v1.0.10
      run: |
        echo "RELEASE_TAG is: " $RELEASE_TAG
        if [[ $RELEASE_TAG =~ ^v1\.[0-9]+\.[0-9]+$ ]]; 
        then
          echo "This is a stable release!"
          echo "::set-output name=is_stable::true"
        else
          echo "This is not a stable release!"
          echo "::set-output name=is_stable::false"
        fi

  deploy:
    name: Deploy gh-pages!
    needs: check-release
    runs-on: ubuntu-latest
    
    # skip deploying to gh-pages if release is not "stable"
    if: ${{ needs.check-release.outputs.is_stable == 'true' }}

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'

    - run: npm ci # do a clean install of all of our dependencies
    - run: npm run build # check if our library can be built without issues

    - name: Deploy to gh-pages # publish our site to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }} # authenticate the action to our workflow
        publish_dir: ./build # this directory will be copied over to gh-pages
